location            = "japaneast"
resource_group_name = "rg-ai-fastapi-local"
environment         = "local"
name_prefix         = "aifs"
auth_mode           = "key"
owner               = "team"
cost_center         = "cc-0000"
